### ISSUE TITLE
when will the dataset be publicly available?

### ISSUE THREAD

**Issue by wangphoebe** [giaabaoo/MTP_pipeline#1]
Hi, 
Nice work! However, the QR code on ACL poster is not publicly available (probably the owner needs to modify the permission?) 
Just here to ask when can we download the dataset for further research?

**Comment by giaabaoo** [comment]
Hi,

Thank you for your interest in our work. You can also find our dataset at this [link](https://drive.google.com/drive/folders/1xz0RwB9WmUCXSMr4SHhH5GvaNQ78IqA4?usp=sharing). We have made it publicly available.

Please note that this is the first version of our release. During the annotation process, we split the dataset into two iterations. Given the recent increase in interest in our work, we plan to spend some time merging the full set (expected to be completed within this month) to make it easier for others to use. We also require users of our dataset to sign a **Data Use Agreement** to ensure confidentiality, data security, restrictions on data sharing, and the prohibition of using the data in ways that would violate copyrights or intellectual property rights. 

I am currently occupied during the week, so I will update the README with a Google Form for the **Data Use Agreement** later this weekend. Many thanks!

**Comment by wangphoebe** [comment]
thx！ 
Please get me informed when the agreement is ready.

**Comment by giaabaoo** [comment]
Hi, sorry for the late reply, and thank you very much for your patience. [Here](https://drive.google.com/file/d/1sHigqVVqr8h5X_wxA2m8sGUB7vvKWxBS/view?usp=sharing) is the Data Usage Agreement. Please sign it and send the signed document back to this email: dinhhogiabao@gmail.com (title: Request access for the MTP Dataset). We will send the full dataset link to your email upon receiving the signed document.
